name := "applicatives"
version := "0.1-SNAPSHOT"
scalaVersion := "2.11.7"
libraryDependencies += "sattar.scala" %% "monad" % "0.1-SNAPSHOT"
libraryDependencies += "sattar.scala" %% "monoid" % "0.1-SNAPSHOT"